In [2]:
import numpy as np

## DataTypes and Attributes

In [3]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
a2 = np.array([5,6,7])
a2

array([5, 6, 7])

In [3]:
a1.dtype

dtype('int32')

In [4]:
a3 = np.array([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
],
[
    [10,11,12],
    [13,14,15],
    [16,17,18]
]])

a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [5]:
type(a3)

numpy.ndarray

## Creating numpy Arrays

In [6]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [7]:
type(sample_array)

numpy.ndarray

In [8]:
sample_array.dtype

dtype('int32')

In [9]:
ones = np.ones((2,3))

In [10]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
type(ones)

numpy.ndarray

In [12]:
range_array = np.arange(1, 24, 3)
range_array

array([ 1,  4,  7, 10, 13, 16, 19, 22])

In [13]:
random_array = np.random.randint(0,10, size=(4,5))
random_array

array([[9, 2, 6, 8, 7],
       [2, 3, 8, 5, 8],
       [2, 7, 9, 2, 4],
       [1, 0, 4, 0, 7]])

## Random Seed

In [14]:
np.random.seed(99999)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [15]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## Viewing arrays and matrices

In [16]:
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [17]:
a3.shape

(2, 3, 3)

In [18]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [19]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Slicing

In [20]:
a3[:2, :3, :2]

array([[[ 1,  2],
        [ 4,  5],
        [ 7,  8]],

       [[10, 11],
        [13, 14],
        [16, 17]]])

## Manipulating Arrays

### Arithmetic

In [21]:
a1

array([1, 2, 3])

In [22]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [23]:
a1 + ones

array([2., 3., 4.])

In [24]:
a1 - ones

array([0., 1., 2.])

In [25]:
a2 = np.array([[1,2,3.3],
             [4,5,6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [26]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [27]:
a1 * a3

array([[[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]],

       [[10, 22, 36],
        [13, 28, 45],
        [16, 34, 54]]])

In [28]:
a3.shape


(2, 3, 3)

In [29]:
a1.shape

(3,)

In [30]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

## Manipulating arrays 2

### Aggregation

In [ ]:
listy_list = [1,2,3]
type(listy_list)

In [ ]:
sum(listy_list)

In [ ]:
a1

In [ ]:
type(a1)

In [ ]:
sum(a1)

In [ ]:
np.sum(a1)

In [ ]:
# Standard deviation (AKA square root of Variance)
np.std(a2)

In [ ]:
# Variance 
np.var(a2)

## Standard Deviation and Variance

In [ ]:
high_var_array = np.array([1,100,200,300,4000,5000])
low_var_array = np.array([2,4,6,8,10])

In [ ]:
np.var(high_var_array), np.var(low_var_array)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

plt.hist(high_var_array)
plt.show()

In [ ]:
plt.hist(low_var_array)
plt.show()

In [ ]:
a2

## Sorting Arrays

In [38]:
random_array = np.random.randint(10, size=(5,3))

In [39]:
random_array

array([[3, 8, 3],
       [0, 1, 0],
       [0, 6, 7],
       [7, 9, 3],
       [0, 7, 7]])

In [40]:
np.argmax(random_array, axis=0)

array([3, 3, 2], dtype=int64)

In [41]:
np.argmax(random_array, axis=1)

array([1, 1, 2, 1, 1], dtype=int64)

## Images to numpy array

In [43]:
from matplotlib.image import imread
panda = imread("panda.png")
print(type(panda))


<class 'numpy.ndarray'>


<img src="panda.png" />

In [44]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [45]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [46]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.